# 数据库的默认账号和密码仅首次运行时设置有效
# 如果修改了账号密码，记得改数据库和项目连接参数，别只改一处~
# 该配置文件只是给快速启动，测试使用。正式使用，记得务必修改账号密码，以及调整合适的知识库参数，共享内存等。
# 如何无法访问 dockerhub 和 git，可以用阿里云（阿里云没有arm包）
version: '3.3'
services:
  redis:
    image: redis:latest
    container_name: redis_gecko
    ports: # 生产环境建议不要暴露
      - 6379:6379
    volumes:
      - ./database/redis/conf:/usr/local/etc/redis
      - ./database/redis/data:/data
    command: redis-server /usr/local/etc/redis/redis.conf
    networks:
      - inefi
  mysql:
    image: mysql:8.0.36
    container_name: mysql_gecko
    restart: always
    ports:
      - 3307:3306
    networks:
      - inefi
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: inefi
      # 默认root密码，仅首次运行有效
      MYSQL_ROOT_PASSWORD: inefi_pwd
    volumes:
      - ./database/mysql:/var/lib/mysql
networks:
  inefi: